bin/sh
2014-05-17
17:42:35.1882|INFO|thread:1|GitHub.ViewModels.SoftwareUpdateViewModel|Checking
for new version
2014-05-17
16:14:21.2544|INFO|thread:1|GitHub.Helpers.CommandLineHandler|Started
app with command:
2014-05-17
16:14:22.9545|INFO|thread:1|GitHub.Models.UserSettingsModel|Refreshing
user settings
2014-05-17
16:14:27.9628|INFO|thread:4|GitHub.Models.UserSettingsModel|Refreshed
user settings
2014-05-17 16:14:30.2539|WARN|thread:6|KeyedOperationQueue|Failure
running queued op
Akavache.Sqlite3.Internal.SQLiteException: no such table: SchemaInfo
at Akavache.Sqlite3.Internal.SQLite3.Prepare2(IntPtr db, String query)
at Akavache.Sqlite3.Internal.SQLiteCommand.Prepare()
at Akavache.Sqlite3.Internal.SQLiteCommand.ExecuteScalar[T]()
at
Akavache.Sqlite3.Internal.SQLiteAsyncConnection.<>c__DisplayClass26`1.<ExecuteScalarAsync>b__25(SQLiteConnection
conn)
at
Akavache.Sqlite3.Internal.SQLiteConnectionPool.<>c__DisplayClass3`1.<EnqueueConnectionOp>b__1()
at Akavache.KeyedOperationQueue.<>c__DisplayClass15`1.<SafeStart>b__14()
2014-05-17 16:14:30.2539|WARN|thread:3|KeyedOperationQueue|Failure
running queued op
Akavache.Sqlite3.Internal.SQLiteException: no such table: SchemaInfo
at Akavache.Sqlite3.Internal.SQLite3.Prepare2(IntPtr db, String query)
at Akavache.Sqlite3.Internal.SQLiteCommand.Prepare()
at Akavache.Sqlite3.Internal.SQLiteCommand.ExecuteScalar[T]()
at
Akavache.Sqlite3.Internal.SQLiteAsyncConnection.<>c__DisplayClass26`1.<ExecuteScalarAsync>b__25(SQLiteConnection
conn)
at
Akavache.Sqlite3.Internal.SQLiteConnectionPool.<>c__DisplayClass3`1.<EnqueueConnectionOp>b__1()
at Akavache.KeyedOperationQueue.<>c__DisplayClass15`1.<SafeStart>b__14()
2014-05-17
16:14:33.7851|INFO|thread:4|GitHub.Models.RepositoryHosts|Cache did not
contain an Enterprise host URI.
System.Collections.Generic.KeyNotFoundException: The given key
'enterprise-host-api-base-uri' was not present in the cache.
2014-05-17
16:14:43.0227|WARN|thread:1|LogHost|SuppressChangeNotifications was
called (perhaps via AddRange), yet you do not
2014-05-17 16:14:43.0227|WARN|thread:1|LogHost|have a subscription to
ShouldReset. This probably isn't what you want, as ItemsAdded
2014-05-17 16:14:43.0227|WARN|thread:1|LogHost|and friends will appear
to 'miss' items
2014-05-17
16:14:45.0488|INFO|thread:3|GitHub.Helpers.PortablePackageManager|Examining
package dir C:\Users\MacBook\AppData\Local\GitHub\Cef_115967
2014-05-17
16:14:46.8239|INFO|thread:1|GitHub.Helpers.CommandLineHandler|Parsing
command line arguments:
2014-05-17
16:14:46.8239|INFO|thread:1|GitHub.Helpers.CommandLineHandler|
http://github-windows.s3.amazonaws.com/GitHub.application
2014-05-17
16:14:46.8759|INFO|thread:1|GitHub.Helpers.AppInstanceCommunicator|Starting
up as master instance of GitHub for Windows
2014-05-17
16:14:47.3909|INFO|thread:1|GitHub.CacheMigrations.SharedCacheToHostCacheMigration|Migrating
shared cache 'C:\Users\MacBook\AppData\Roaming\GitHub\BlobCache' to
host-specific cache
'C:\Users\MacBook\AppData\Local\GitHub\BlobCache.api.github.com'.
2014-05-17
16:14:47.3909|INFO|thread:1|GitHub.CacheMigrations.SharedCacheToHostCacheMigration|Shared
cache 'C:\Users\MacBook\AppData\Roaming\GitHub\BlobCache' doesn't exist.
2014-05-17
16:14:47.3909|INFO|thread:1|GitHub.CacheMigrations.SharedCacheToHostCacheMigration|Migrating
shared cache 'C:\Users\MacBook\AppData\Local\GitHub\BlobCache' to
host-specific cache
'C:\Users\MacBook\AppData\Roaming\GitHub\BlobCache.api.github.com'.
2014-05-17
16:14:47.3909|INFO|thread:1|GitHub.CacheMigrations.SharedCacheToHostCacheMigration|Shared
cache 'C:\Users\MacBook\AppData\Local\GitHub\BlobCache' doesn't exist.
2014-05-17 16:14:51.9592|INFO|thread:4|GitHub.AppStartup.StartupLogging|
#########################################
2014-05-17 16:14:51.9592|INFO|thread:4|GitHub.AppStartup.StartupLogging|
GitHub for Windows started. VERSION: 1.3.3.1
2014-05-17 16:14:51.9592|INFO|thread:4|GitHub.AppStartup.StartupLogging|
Build version: 0f9c06fa5d1cd6052710ab8ce31822f6269cb6a7
2014-05-17 16:14:51.9592|INFO|thread:4|GitHub.AppStartup.StartupLogging|
***************************************
2014-05-17 16:14:51.9592|INFO|thread:4|GitHub.AppStartup.StartupLogging|
***                                 ***
2014-05-17 16:14:51.9592|INFO|thread:4|GitHub.AppStartup.StartupLogging|
***                                 ***
2014-05-17 16:14:51.9592|INFO|thread:4|GitHub.AppStartup.StartupLogging|
***        Have a problem?          ***
2014-05-17 16:14:51.9592|INFO|thread:4|GitHub.AppStartup.StartupLogging|
***    Email support@github.com     ***
2014-05-17 16:14:51.9592|INFO|thread:4|GitHub.AppStartup.StartupLogging|
***      and include this file      ***
2014-05-17 16:14:51.9592|INFO|thread:4|GitHub.AppStartup.StartupLogging|
***                                 ***
2014-05-17 16:14:51.9592|INFO|thread:4|GitHub.AppStartup.StartupLogging|
***                                 ***
2014-05-17 16:14:51.9592|INFO|thread:4|GitHub.AppStartup.StartupLogging|
***************************************
2014-05-17 16:14:51.9592|INFO|thread:4|GitHub.AppStartup.StartupLogging|
OS Version: Windows 7 Service Pack 1 6.1.7601.65536 x86
2014-05-17 16:14:51.9592|INFO|thread:4|GitHub.AppStartup.StartupLogging|
CLR Version: 4.0.30319.18444
2014-05-17 16:14:51.9592|INFO|thread:4|GitHub.AppStartup.StartupLogging|
Current culture: ar-SA
2014-05-17 16:14:52.0562|INFO|thread:4|GitHub.AppStartup.StartupLogging|
Terminal Services session: no
2014-05-17 16:14:52.0562|INFO|thread:4|GitHub.AppStartup.StartupLogging|
Location:
C:\Users\MacBook\AppData\Local\Apps\2.0\77Z1OZ9G.O6W\YJNVRTA3.Q8Y\gith..tion_317444273a93ac29_0001.0003_e68db37a99107794\GitHub.exe
2014-05-17
16:14:53.2152|INFO|thread:6|GitHub.UI.Helpers.HardwareRenderingHelper|Making
a WMI query to discover any video PNPID entries
2014-05-17 16:14:59.0696|INFO|thread:4|GitHub.AppStartup.StartupLogging|
ActivationUri:
https://github-windows.s3.amazonaws.com/GitHub.application
2014-05-17
16:14:59.3566|INFO|thread:4|GitHub.PortableGit.Helpers.GitEnvironment|Process
set up with this SSH Agent info: (null):(null)
2014-05-17
16:14:59.3566|INFO|thread:4|GitHub.PortableGit.Helpers.GitEnvironment|PATH
is
C:\Users\MacBook\AppData\Local\GitHub\PortableGit_054f2e797ebafd44a30203088cd3d58663c627ef\cmd;C:\Users\MacBook\AppData\Local\GitHub\PortableGit_054f2e797ebafd44a30203088cd3d58663c627ef\bin;C:\Users\MacBook\AppData\Local\Apps\2.0\77Z1OZ9G.O6W\YJNVRTA3.Q8Y\gith..tion_317444273a93ac29_0001.0003_e68db37a99107794;C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program
Files\QuickTime\QTSystem\
2014-05-17 16:14:59.3726|INFO|thread:4|GitHub.AppStartup.StartupLogging|
=====================================================
2014-05-17 16:14:59.3726|INFO|thread:4|GitHub.AppStartup.StartupLogging|
DIAGNOSTICS                                        |
2014-05-17 16:14:59.3726|INFO|thread:4|GitHub.AppStartup.StartupLogging|
=====================================================
2014-05-17 16:14:59.3726|INFO|thread:4|GitHub.AppStartup.StartupLogging|
Git Extracted: 'False:
2014-05-17
16:14:59.3836|ERROR|thread:4|GitHub.AppStartup.StartupLogging| MISSING
PortableGit Dir:
'C:\Users\MacBook\AppData\Local\GitHub\PortableGit_054f2e797ebafd44a30203088cd3d58663c627ef'
2014-05-17
16:14:59.5236|ERROR|thread:4|GitHub.PortableGit.Helpers.PortableGitManager|git.exe
doesn't exist at
'C:\Users\MacBook\AppData\Local\GitHub\PortableGit_054f2e797ebafd44a30203088cd3d58663c627ef\bin\git.exe'
2014-05-17
16:14:59.5236|ERROR|thread:4|GitHub.AppStartup.StartupLogging| MISSING
Git Executable:
'C:\Users\MacBook\AppData\Local\GitHub\PortableGit_054f2e797ebafd44a30203088cd3d58663c627ef\bin\git.exe'
2014-05-17
16:14:59.5236|ERROR|thread:4|GitHub.AppStartup.StartupLogging| MISSING
PATH!!:
'C:\Users\MacBook\AppData\Local\GitHub\PortableGit_054f2e797ebafd44a30203088cd3d58663c627ef\cmd'
2014-05-17
16:14:59.5236|ERROR|thread:4|GitHub.AppStartup.StartupLogging| MISSING
PATH!!:
'C:\Users\MacBook\AppData\Local\GitHub\PortableGit_054f2e797ebafd44a30203088cd3d58663c627ef\bin'
2014-05-17 16:14:59.5236|INFO|thread:4|GitHub.AppStartup.StartupLogging|
----------------------------------------------------
2014-05-17 16:14:59.5236|INFO|thread:4|GitHub.AppStartup.StartupLogging|
PATH:
C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program
Files\QuickTime\QTSystem\
2014-05-17
16:15:01.5447|INFO|thread:4|GitHub.Helpers.StartupLogger|Proxy
information: (None)
2014-05-17
16:15:01.5447|INFO|thread:4|GitHub.Helpers.StartupLogger|Couldn't fetch
creds for proxy
2014-05-17
16:15:02.1807|INFO|thread:4|GitHub.Helpers.UrlProtocolInstaller|Registered
UrlAppLauncher protocol:
"C:\Users\MacBook\AppData\Local\Apps\2.0\77Z1OZ9G.O6W\YJNVRTA3.Q8Y\gith..tion_317444273a93ac29_0001.0003_e68db37a99107794\GitHub.exe"
-u="%1"
2014-05-17
16:15:02.4448|INFO|thread:4|GitHub.Helpers.ShortcutManager|Shortcut
'C:\Users\MacBook\AppData\Local\GitHub\GitHub.appref-ms' missing.
Assuming a first run.
2014-05-17
16:15:02.6698|INFO|thread:4|GitHub.Helpers.ShortcutManager|Copying the
Start Menu shortcut
'C:\Users\MacBook\AppData\Roaming\Microsoft\Windows\Start
Menu\Programs\GitHub, Inc\GitHub.appref-ms' to
'C:\Users\MacBook\AppData\Local\GitHub\GitHub.appref-ms'
2014-05-17
16:15:06.1220|INFO|thread:4|GitHub.Helpers.ShortcutManager|Saving the
Git Shell shortcut
C:\Users\MacBook\AppData\Roaming\Microsoft\Windows\Start
Menu\Programs\GitHub, Inc\Git Shell.lnk
2014-05-17
16:15:07.1090|INFO|thread:4|GitHub.Helpers.ShortcutManager|Saving the
Git Shell shortcut C:\Users\MacBook\Desktop\Git Shell.lnk
2014-05-17
16:15:08.7841|INFO|thread:1|GitHub.UI.Helpers.HardwareRenderingHelper|Your
video card appears to support hardware rendering. If this isn't the case
and you see glitches
2014-05-17
16:15:08.7841|INFO|thread:1|GitHub.UI.Helpers.HardwareRenderingHelper|set
the GH_FORCE_SW_RENDERING environment variable to 1
2014-05-17 16:15:08.7971|INFO|thread:1|GitHub.App|Checking whether
application is network deployed.
2014-05-17
16:15:19.2047|INFO|thread:1|GitHub.Helpers.ClickOnceAppIconHelper|Updating
registry with our application icon
'C:\Users\MacBook\AppData\Local\Apps\2.0\77Z1OZ9G.O6W\YJNVRTA3.Q8Y\gith..tion_317444273a93ac29_0001.0003_e68db37a99107794\Images\App.ico'
2014-05-17
16:15:29.6383|INFO|thread:14|GitHub.ViewModels.SoftwareUpdateViewModel|Checking
for new version
2014-05-17
16:15:58.1529|WARN|thread:1|POCOObservableForProperty|GitHub.Views.TwoFactorView
is a POCO type and won't send change notifications, WhenAny will only
return a single value!
2014-05-17
16:15:58.8630|WARN|thread:1|POCOObservableForProperty|GitHub.Views.UndoFlashView
is a POCO type and won't send change notifications, WhenAny will only
return a single value!
2014-05-17
16:15:59.2980|WARN|thread:1|POCOObservableForProperty|GitHub.Views.ShellView
is a POCO type and won't send change notifications, WhenAny will only
return a single value!
2014-05-17
16:16:04.2963|WARN|thread:1|POCOObservableForProperty|GitHub.Views.Controls.OptionsMenu
is a POCO type and won't send change notifications, WhenAny will only
return a single value!
2014-05-17
16:16:05.0623|INFO|thread:1|GitHub.Extensions.ReactiveScreen|Activating
GitHub.ViewModels.ShellViewModel.
2014-05-17
16:16:05.0793|INFO|thread:8|GitHub.ViewModels.GitExtractionVisualHelper|Attempting
to extract Portable Git.
2014-05-17
16:16:05.1373|INFO|thread:1|GitHub.Extensions.ReactiveScreen|Activating
GitHub.ViewModels.DashboardViewModel.
2014-05-17
16:16:05.1373|INFO|thread:8|GitHub.IO.ObservableProcess|Starting:
Process - FileName:
'C:\Users\MacBook\AppData\Local\Apps\2.0\77Z1OZ9G.O6W\YJNVRTA3.Q8Y\gith..tion_317444273a93ac29_0001.0003_e68db37a99107794\7za.exe',
Args: 'x -y "-oC:\Users\MacBook\AppData\Local\GitHub\ylj2sswb.2le"
"C:\Users\MacBook\AppData\Local\Apps\2.0\77Z1OZ9G.O6W\YJNVRTA3.Q8Y\gith..tion_317444273a93ac29_0001.0003_e68db37a99107794\PortableGit.7z"'
2014-05-17
16:16:07.1475|INFO|thread:8|GitHub.Helpers.PortablePackageManager|Extracting
PortableGit.7z is (so far) successful
2014-05-17
16:16:39.6793|WARN|thread:1|LogHost|SuppressChangeNotifications was
called (perhaps via AddRange), yet you do not
2014-05-17 16:16:39.6793|WARN|thread:1|LogHost|have a subscription to
ShouldReset. This probably isn't what you want, as ItemsAdded
2014-05-17 16:16:39.6793|WARN|thread:1|LogHost|and friends will appear
to 'miss' items
2014-05-17
16:16:47.6678|WARN|thread:1|POCOObservableForProperty|GitHub.Views.Controls.Login
is a POCO type and won't send change notifications, WhenAny will only
return a single value!
2014-05-17
16:16:49.3999|INFO|thread:1|GitHub.Extensions.ReactiveScreen|Activating
GitHub.ViewModels.WelcomeWizardViewModel.
2014-05-17
16:21:09.2607|INFO|thread:6|GitHub.Helpers.PortablePackageManager|GitHub.IO.ObservableProcess
2014-05-17
16:21:15.7081|INFO|thread:24|GitHub.Helpers.PortablePackageManager|Examining
package dir C:\Users\MacBook\AppData\Local\GitHub\Cef_115967
2014-05-17
16:21:15.7081|INFO|thread:24|GitHub.Helpers.PortablePackageManager|Examining
package dir
C:\Users\MacBook\AppData\Local\GitHub\PortableGit_054f2e797ebafd44a30203088cd3d58663c627ef
2014-05-17
16:21:16.1831|INFO|thread:6|GitHub.Helpers.GitHubShellSetupHelper|Wrote
GitHubShell setup script here
'C:\Users\MacBook\AppData\Local\GitHub\shell.ps1'
2014-05-17 16:43:45.4663|INFO|thread:21|GitHub.Helpers.GitConfig|Reading
global git configuration for user.name and user.email
2014-05-17
16:43:46.1134|INFO|thread:21|GitHub.ConfigurationFactory|Didn't find
'~/.gitconfig', creating one.
2014-05-17 16:43:48.7575|INFO|thread:21|GitHub.Helpers.GitConfig|Setting
default global git configuration for user.name b/c it was blank. value =
moro5554
2014-05-17
16:43:48.9445|INFO|thread:19|GitHub.ViewModels.ApplicationShellInitializer|Running
post login tasks. ~/.gitconfig is set up with user.name = 'moro5554' and
user.email = ''
2014-05-17 16:43:48.9455|INFO|thread:22|GitHub.Helpers.GitConfig|Reading
global git configuration for user.name and user.email
2014-05-17
16:43:50.7426|INFO|thread:25|GitHub.PortableGit.Helpers.SSHProcessManager|Starting
ssh-agent.exe
2014-05-17
16:43:51.0346|INFO|thread:22|GitHub.PortableGit.Helpers.SSHKeyHelper|Couldn't
find SSH key pair, generating new ones
2014-05-17
16:43:52.1727|INFO|thread:25|GitHub.PortableGit.Helpers.GitEnvironment|Process
set up with this SSH Agent info: (null):(null)
2014-05-17
16:43:52.1727|INFO|thread:25|GitHub.PortableGit.Helpers.GitEnvironment|PATH
is
C:\Users\MacBook\AppData\Local\GitHub\PortableGit_054f2e797ebafd44a30203088cd3d58663c627ef\cmd;C:\Users\MacBook\AppData\Local\GitHub\PortableGit_054f2e797ebafd44a30203088cd3d58663c627ef\bin;C:\Users\MacBook\AppData\Local\Apps\2.0\77Z1OZ9G.O6W\YJNVRTA3.Q8Y\gith..tion_317444273a93ac29_0001.0003_e68db37a99107794;C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\Windows\System32
2014-05-17
16:43:52.2457|INFO|thread:22|GitHub.PortableGit.Helpers.GitEnvironment|Process
set up with this SSH Agent info: (null):(null)
2014-05-17
16:43:52.2457|INFO|thread:22|GitHub.PortableGit.Helpers.GitEnvironment|PATH
is
C:\Users\MacBook\AppData\Local\GitHub\PortableGit_054f2e797ebafd44a30203088cd3d58663c627ef\cmd;C:\Users\MacBook\AppData\Local\GitHub\PortableGit_054f2e797ebafd44a30203088cd3d58663c627ef\bin;C:\Users\MacBook\AppData\Local\Apps\2.0\77Z1OZ9G.O6W\YJNVRTA3.Q8Y\gith..tion_317444273a93ac29_0001.0003_e68db37a99107794;C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\Windows\System32
2014-05-17
16:43:52.8387|INFO|thread:22|GitHub.IO.ObservableProcess|Starting:
Process - FileName:
'C:\Users\MacBook\AppData\Local\GitHub\PortableGit_054f2e797ebafd44a30203088cd3d58663c627ef\bin\ssh-keygen.exe',
Args: '-t rsa -N "" -f "C:\Users\MacBook\.ssh\github_rsa"'
2014-05-17
16:43:52.8897|INFO|thread:25|GitHub.IO.ObservableProcess|Starting:
Process - FileName:
'C:\Users\MacBook\AppData\Local\GitHub\PortableGit_054f2e797ebafd44a30203088cd3d58663c627ef\bin\ssh-agent.exe',
Args: ''
2014-05-17 16:44:08.9427|INFO|thread:19|GitHub.Helpers.GitConfig|Saving
global git configuration for user.name and user.email
2014-05-17
16:44:08.9597|INFO|thread:19|GitHub.Helpers.GitConfig|Changing global
git configuration for user.email. value = bebo-00966@hotmail.com
2014-05-17
16:44:10.0157|INFO|thread:1|GitHub.Extensions.ReactiveScreen|Deactivating
GitHub.ViewModels.WelcomeWizardViewModel.
2014-05-17
16:44:10.2777|INFO|thread:1|GitHub.Extensions.ReactiveScreen|Closed
GitHub.ViewModels.WelcomeWizardViewModel.
2014-05-17
16:44:13.7669|INFO|thread:25|GitHub.PortableGit.Helpers.GitEnvironment|Process
set up with this SSH Agent info: 8644:/tmp/ssh-idTzbK8616/agent.8616
2014-05-17
16:44:13.7669|INFO|thread:25|GitHub.PortableGit.Helpers.GitEnvironment|PATH
is
C:\Users\MacBook\AppData\Local\GitHub\PortableGit_054f2e797ebafd44a30203088cd3d58663c627ef\cmd;C:\Users\MacBook\AppData\Local\GitHub\PortableGit_054f2e797ebafd44a30203088cd3d58663c627ef\bin;C:\Users\MacBook\AppData\Local\Apps\2.0\77Z1OZ9G.O6W\YJNVRTA3.Q8Y\gith..tion_317444273a93ac29_0001.0003_e68db37a99107794;C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\Windows\System32
2014-05-17
16:44:13.7669|INFO|thread:25|GitHub.IO.ObservableProcess|Starting:
Process - FileName:
'C:\Users\MacBook\AppData\Local\GitHub\PortableGit_054f2e797ebafd44a30203088cd3d58663c627ef\bin\ssh-add.exe',
Args: '"C:\Users\MacBook\.ssh\github_rsa"'
2014-05-17 16:44:14.9270|INFO|thread:23|GitHub.Api.ApiClient|About to
add SSH Key: GitHub for Windows - MacOS - ssh-rsa
AAAAB3NzaC1yc2EAAAABIwAAAQEArulPv4KqQPnbZ9IZgrxUSpUpVPFA48OyI8WtKo3yP7fPZyB7W7hNy708ExSD0PP8oA51NetzBHKRjmYchkXnQNQMYNhyfScUDzrTK+zRBE/Lqb5s1MiXn61VgXUZyNTcuFv6GNT7GcwrnpDOC2LLCL9ZTClgnSI6MmcIqgCugY5dMRv4uBMT8cBl50ovZVdH3zFrM1d0WmnP3vYVVDlHKBLPbggLWgEoY6o3z62B2WvRIY1oeGjTIdA0ZVAhNjJFoMhdWxTnY/X3k+skOZ97HF760LQDaSOS1jJ+L519moOjLY1BkvM15nkOME1T2ux2B00pOkQtb3kru5qgqH5+lQ==
MacBook@MACOS

2014-05-17
16:44:29.5068|WARN|thread:1|POCOObservableForProperty|GitHub.Views.Controls.LicenseBrowser
is a POCO type and won't send change notifications, WhenAny will only
return a single value!
2014-05-17
16:44:30.5279|WARN|thread:1|POCOObservableForProperty|GitHub.Views.AboutView
is a POCO type and won't send change notifications, WhenAny will only
return a single value!
2014-05-17
16:44:32.7160|WARN|thread:1|POCOObservableForProperty|GitHub.Models.ChangeLog
is a POCO type and won't send change notifications, WhenAny will only
return a single value!
2014-05-17
16:44:33.1550|INFO|thread:1|GitHub.Extensions.ReactiveScreen|Activating
GitHub.ViewModels.AboutViewModel.
2014-05-17
16:44:39.9734|INFO|thread:1|GitHub.ViewModels.SoftwareUpdateViewModel|Checking
for new version
2014-05-17
17:04:13.8006|INFO|thread:1|GitHub.Extensions.ReactiveScreen|Deactivating
GitHub.ViewModels.AboutViewModel.
2014-05-17
17:04:13.9556|INFO|thread:1|GitHub.Extensions.ReactiveScreen|Closed
GitHub.ViewModels.AboutViewModel.
2014-05-17
17:40:09.5279|INFO|thread:1|GitHub.Extensions.ReactiveScreen|Activating
GitHub.ViewModels.NewRepositoryViewModel.
2014-05-17
17:42:16.8452|INFO|thread:1|GitHub.ViewModels.NewRepositoryViewModel|Creating
and initializing new local repository here
'C:\Users\MacBook\Documents\GitHub\afc2c'
2014-05-17
17:42:19.9213|INFO|thread:1|GitHub.ViewModels.NewRepositoryViewModel|Succeeded:
'C:\Users\MacBook\Documents\GitHub\afc2c\.git\'
2014-05-17
17:42:20.3274|INFO|thread:1|GitHub.ViewModels.NewRepositoryViewModel|Creating
on https://api.github.com/ in account 'moro5554'
2014-05-17
17:42:27.5088|INFO|thread:1|GitHub.Extensions.ReactiveScreen|Deactivating
GitHub.ViewModels.NewRepositoryViewModel.
2014-05-17
17:42:27.5088|INFO|thread:1|GitHub.Extensions.ReactiveScreen|Closed
GitHub.ViewModels.NewRepositoryViewModel.
2014-05-17
17:42:35.0882|INFO|thread:1|GitHub.Extensions.ReactiveScreen|Activating
GitHub.ViewModels.AboutViewModel.